# Generated by Django 5.1.6 on 2025-06-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similarity_search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
